main:
	clang++ -O0 -std=c++11 main.cpp -o build/main -Wall -Wextra
	clang++ -O2 -std=c++11 main.cpp -o build/main-O2 -Wall -Wextra
	clang++ -O3 -std=c++11 main.cpp -o build/main-O3 -Wall -Wextra
	clang++ -Os -std=c++11 main.cpp -o build/main-Os -Wall -Wextra
	clang++ -Oz -std=c++11 main.cpp -o build/main-Oz -Wall -Wextra
clean:
	rm  ./build/*
